export * from './blankary/blankary.module'
export * from './comick/comick.module'
export * from './imgur/imgur.module'
export * from './mangadex/mangadex.module'
export * from './nhentai/nhentai.module'
export * from './pixiv/pixiv.module'
export * from './reddit/reddit.module'
export * from './telegraph/telegraph.module'
export * from './yandere/yandere.module'
export * from './zenko/zenko.module'
// link to json data
export * from './read/read.module'